spring:
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookshelf
  application:
    name: bookshelf
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp